# Generated by Django 5.0.6 on 2024-07-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_picture",
            field=models.ImageField(default="default_cover.png", upload_to=""),
        ),
    ]
