# Generated by Django 5.0.6 on 2024-07-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_cover_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_picture",
            field=models.ImageField(default="cover_picture.png", upload_to=""),
        ),
    ]
