# Generated by Django 5.0.6 on 2024-07-03 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_cover_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
